config/routes.rb
Rails.application.routes.draw do
  root 'trending_devs#index'

  post 'trending_devs/search_languages', :to => 'trending_devs#search_languages'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trending_dev.rb
class TrendingDev < ApplicationRecord
  include HTTParty

  def get_trending_dev_data(params = nil)
    language = params[:language] if params
    frequency = params[:frequency] if params
    begin
      self.class.get(ENV['TRENDING_API']+"?language=#{language}&since=#{frequency}")
    rescue
      "Unable to get api results"
    end
  end

  def latest_trending_devs(params = nil)
    get_trending_dev_data(params).parsed_response
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trending_devs_controller.rb
class TrendingDevsController < ApplicationController

  def index
    @trending_devs = TrendingDev.new.latest_trending_devs
  end

  def search_languages
    search_params = {:language => params['language'], :frequency => params['frequency']}
    @language = params['language']
    @trending_devs = TrendingDev.new.latest_trending_devs(search_params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trending_devs_helper.rb
module TrendingDevsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrendingDevs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trending_devs/index.html.erb
<p>
  <%= form_tag trending_devs_search_languages_path do %>
    <div>
      Language : <%= text_field_tag :language %>
    </div>
    <div>
      Frequency : <%= text_field_tag :frequency %>
    </div>
    <div class="actions">
      <%= submit_tag "Submit", :name => nil %>
    </div>
  <% end %>
</p>

<h1>TrendingDevs!!</h1>

<%@trending_devs.each do |proj| %>
  <div>Author : <%= proj["author"]%></div>
  <div>Name : <%= proj["name"]%></div>
  <div>Avatar : <%= proj["avatar"]%></div>
  <div>Language : <%= proj["language"]%></div>
  <div>Url : <%= proj["url"]%></div>
  <div>Stars : <%= proj["stars"]%>
  <div>Description : <%= proj["description"]%></div>
  <div>Built by:
    <%proj["builtBy"].each do |author|%>
      <%= author["username"]%>
    <%end%>
  </div>
  <br><br>
<%end%>

app/views/trending_devs/search_languages.html.erb
<div><%= link_to "Back to Home", root_path, :method => :get %></div>

<h4>TrendingDevs in <%= @language%></h4>

<%@trending_devs.each do |proj| %>
  <div>Author : <%= proj["author"]%></div>
  <div>Name : <%= proj["name"]%></div>
  <div>Avatar : <%= proj["avatar"]%></div>
  <div>Language : <%= proj["language"]%></div>
  <div>Url : <%= proj["url"]%></div>
  <div>Stars : <%= proj["stars"]%>
  <div>Description : <%= proj["description"]%></div>
    <div>Built by:
    <%proj["builtBy"].each do |author|%>
      <%= author["username"]%>
    <%end%>
  </div>
  <br><br>
<%end%>